# Generated by Django 3.0.5 on 2020-07-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200708_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
