# Generated by Django 3.0.5 on 2020-07-15 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20200715_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_vote',
        ),
        migrations.AddField(
            model_name='product',
            name='end_user_set',
            field=models.ManyToManyField(blank=True, related_name='end_prods', through='main.End', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_prods', through='main.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
